name: Customer Churn MLOps CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check Python imports
        run: |
          python -c "import pandas, sklearn, imblearn, fastapi, uvicorn, mlflow"

      - name: Check FastAPI app imports
        run: |
          python -c "from app import app; print('FastAPI app import successful')"
          